name: Manual Workflow
on: workflow_dispatch
jobs:
  base64:
      name: Recover With Base64
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v3
        - env:
            MY_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
            MY_DMW: ${{ secrets.COSIGN_PASSWORD }}
          run: |
            echo "starting up..."
  
